name: Main
on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.1"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rspec --require spec_helper

      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/coverage.json
